feat: check deps for python frontend (#3782)
Checks that ast2json is installed and available. If not then exits.
Warns about mypy. Additionally switch to argparse for argument parsing
as that's standard in Python.

This is much more user friendly and doesn't expose the user to a trace.

Example output:

```sh
./build/src/esbmc/esbmc test.py 
[CONFIG] loaded color = true
ESBMC version 8.1.0 64-bit x86_64 linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
[PROGRESS] Parsing test.py
Warning: Missing optional Python package(s): mypy
  Install with: pip3 install mypy
ERROR: Missing required Python package(s): ast2json
  Install with: pip3 install ast2json
```

---------

Co-authored-by: Lucas C. Cordeiro <lucasccordeiro@gmail.com>