[python] add missing return statement detection (#2752)
This PR detects functions with missing return statements on execution
paths and reports them as verification failures instead of allowing them
to pass. In particular, this PR:

- Adds `function_has_missing_return_paths()` to analyze control flow
- Insert `assert(false)` when missing returns are detected
- Add descriptive error messages using location properties
- Properly exclude constructors which don't need explicit returns

Fixes issue where functions such as:
````Python
import random

def absolute(x:int) -> int:
    if (x < 0): return -x
    else: x

x = random.randint(1, 1000)
if (x*x + x*x*x*x) == 90:
    a = absolute(absolute(x))
````

With this PR, ESBMC provides:

````
ESBMC version 7.10.0 64-bit x86_64 Linux
Target: 64-bit little-endian x86_64-unknown-linux with esbmclibc
Parsing main.py

Type checking warning:
main.py:3: error: Missing return statement
Found 1 error in 1 file (checked 1 source file)

Converting
Generating GOTO Program
GOTO program creation time: 2.005s
GOTO program processing time: 0.020s
Starting Bounded Model Checking
Symex completed in: 0.004s (14 assignments)
Slicing time: 0.000s (removed 3 assignments)
Generated 2 VCC(s), 2 remaining after simplification (11 assignments)
No solver specified; defaulting to Boolector
Encoding remaining VCC(s) using bit-vector/floating-point arithmetic
Encoding to solver time: 0.003s
Solving with solver Boolector 3.2.2
Runtime decision procedure: 0.013s
Building error trace

[Counterexample]


State 1 file random.py line 6 column 4 function randint thread 0
----------------------------------------------------
  value = 3 (00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000011)

State 3 file main.py line 3 column 0 function absolute thread 0
----------------------------------------------------
Violated property:
  file main.py line 3 column 0 function absolute
  Missing return statement detected in function 'absolute'
  0


VERIFICATION FAILED
````

---------

Signed-off-by: Lucas Cordeiro <lucasccordeiro@gmail.com>