[util] avoid compiler limit: blocks nested too deeply (#3474)
In "migrate" method, the following structure was used:

```cpp
if (id == 1) 
{
  ...
}
else if (id == 2) 
{
  ...
} 
else if (id == 3) 
{
  ...
} 
```
As we introduce more ireps, this structure reaches the limit of the
compiler's capabilities: `error C1061: compiler limit: blocks nested too
deeply`

Therefore, in this PR, the structure is modified as follows:

```cpp
if (id == 1) 
{
  ...
  return;
}

if (id == 2) 
{
  ...
  return;
} 
```