[regression] mark known bug: regression/mathsat/github_1070
MathSAT v5.5.4 fails on this example now when building the error trace
with

  ERROR: Error creating SMT
  ERROR: Error text: "Invalid model"

in mathsat_convt::get_bool() for this smt_astt:

  (set-info :source |printed by MathSAT|)
  (assert false)

Noteworthy, msat_get_model_value() already spews out a huge amount of
internal mathsat representation.