[C++ verification] adjust lambda operator (#2165)
Here is AST for lambda expr:
```c
| |       `-LambdaExpr 0x6f82f10 <col:28, line:22:9> '(lambda at main6.cpp:19:28)'
| |         |-CXXRecordDecl 0x6f82a78 <line:19:28> col:28 implicit class definition
| |         | |-DefinitionData lambda pass_in_registers standard_layout trivially_copyable literal can_const_default_init
| |         | | |-DefaultConstructor
| |         | | |-CopyConstructor simple trivial has_const_param needs_implicit implicit_has_const_param
| |         | | |-MoveConstructor exists simple trivial needs_implicit
| |         | | |-CopyAssignment trivial has_const_param needs_implicit implicit_has_const_param
| |         | | |-MoveAssignment
| |         | | `-Destructor simple irrelevant trivial
| |         | |-CXXMethodDecl 0x6f82bc0 <col:35, line:22:9> line:19:28 used constexpr operator() 'void () const' inline
| |         | | `-CompoundStmt 0x6f82d18 <line:20:9, line:22:9>
| |         | |   `-UnaryOperator 0x6f82d00 <line:21:13, col:17> 'int' postfix '++'
| |         | |     `-MemberExpr 0x6f82cd0 <col:13> 'int' lvalue ->data 0x6f828a8
| |         | |       `-CXXThisExpr 0x6f82cc0 <col:13> 'classB *' implicit this
| |         | |-FieldDecl 0x6f82e98 <line:19:29> col:29 implicit 'classB *'
| |         | `-CXXDestructorDecl 0x6f82f40 <col:28> col:28 implicit referenced ~(lambda at main6.cpp:19:28) 'void () noexcept' inline default trivial
```

When parsing the operator, the AST declares the original variable
(this->data), however we should use a member variable (__this) from the
lambda class, so we try to replace the operator expression in this PR.

Before:
```
operator() (c:@S@classB@F@foo#@Sa@F@operator()#1):
        // 30 file main6.cpp line 21 column 13 function operator()
        ASSIGN this->data=this->data + 1;                      
        // 31 file main6.cpp line 22 column 9 function operator()
        END_FUNCTION // operator()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
failed: "data" is not a member of lambda
```

this PR:
```
operator() (c:@S@classB@F@foo#@Sa@F@operator()#1):
        // 30 file main6.cpp line 21 column 13 function operator()
        ASSIGN this->__this->data=this->__this->data + 1;
        // 31 file main6.cpp line 22 column 9 function operator()
        END_FUNCTION // operator()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I tried to be as robust as possible, but the AST provides very limited
information, and I expected better methods.