[regression] only 32-bit version of cbmc/01_cbmc_Malloc2 works on windows
Error:
> D:/a/esbmc/esbmc/regression/cbmc\01_cbmc_Malloc2\main.c:1:25: error: typedef redefinition with different types ('unsigned int' vs 'unsigned long long')
> typedef unsigned int    size_t;